env:
  global:
  # ANDROID_SIGNING_PASSWORD
  - secure: KmZ88eIr9tDOGXqY1LXzAkjonEm2PxzV2X7lhsBDo7x1AjdEumN8Q6Ekp9AxJ2iNhdDlEgmv/4FVzm9pq1Jd6FcQvzqtNTcyDtIOiIECSb6CKmKjAo/u6rQk7AoIQ98AjVxV5Ksr9Xal8DRphEHghc9KPx1tmuqS1N4tEgd5YiKm/1A8kHH+ZypBk5hoxjF1GIg1d/TLxVQnhNgJDlZSwLVPNK9+ZSpT+7A79YlzZMAqPyrChHJOd/JYr+fbP/C57iel3C13VbeBWwK7YB6HbQrIEAp68sr8s68mOeg47Y4SWqRF7mP2JGzb8hiD+f7H6EkWE7zKn6GMNuQRWE3olcAcigUkPaFu1aFeuN/KCsDYjLddl/v8buMZS30XEJPi7+XtTXDgQflKcbl5tkiLQd8S6GRupcwVatv8K/cQMFVhfHdXk45ZYSfkngI6+WYxBMgBPEeXwWopUkD+fmuCjhPmoUHbLU5JDaAotHs7wLqCYCI+JC7bQ34AevFifC+If3uU6o2sX6VIM27Jls/56tFfC0jU2Ld9qvvvVLx+lMckefFUpZ2Mn26pnWtN8j/RAacMPLNYn3FQ4gL5j2AbfcQByrjZX9yDvNzcTrCTuWhY9T4Hf9Jv7VeTiZ6ADrwkOxUSafA4237v2YoIqq7hpt7WLwlvNlIFTfmMTd8DGKg=
  # SECRET
  - secure: ej3pGEk9P+fn7ygQcY/sovLdNIA+Xy/M2cZHRPfI/mqFZ04sS2bXANRm7FtuoxCi2pCrL0jL9X5erGPyz9gvW9hxDxyrqALiVLsfni2Fc08OrbMVJcAGgv8S7Oz8mIX6w4vWMKlP9h7XEg9LHBAcqQ81mh+pMAmCThuUFp8dHx8S8+ShGQeqN2sEpFJgy9UQ0Mayo5WNWHYkRvHJ388GgpGIECW+dPuwNQu3Tr1sUAYkzMpzOCX6LEdJJ765Tvk0GsiXSfrgTAtEq1LKZ/5keiUsbhxe5ia+AS2SFq0CYjEg0ijckDU45U1OO6viNphtU9ITHUMZFUuB6O3TrufRy3SqECfzWq5tQTy0/ZlqFJcaa65tjGCqlRfMi6aD9FDmfBUEGxWDL+PNaM9fzQRJyzpm85zcs0m0r4yFU3TDvnzq74rJ7YlyLdC2GvaO7qnYsnMGT+bONBwZzDHw9w4+Mx/pL5aahHJNCMvHVNZct4ruMLl/xiUPAXyblT3QEZPi18gPowwiTAJ782pYAK0zQzw/gJCMh5UsrxEYYC11fbQWtwbPruk2UYhC+e/yIEnNpDxB1rSt+OdlhSwnuuUZjudnihaP9whj+BNa/+IqcPbUGozfhV6BiBCUgAy3fr6z9sOnGpJSviRDWgd+GdpaVh9J+g9RiXU59GB1hlnURoM=

language: java

before_install:
- openssl aes-256-cbc -K $encrypted_e375928ce4bc_key -iv $encrypted_e375928ce4bc_iv
  -in config/a11y-ally-release.jks.enc -out config/a11y-ally-release.jks
  -d

script:
- ./gradlew

deploy:
  provider: releases
  api_key:
    secure: aWc/75tkbiVuve/Tbg9U4wB/Mm4id8IXcgVm4YsQZxHKxouaOo44gCksjINdJP99WOcG8Oq/slKykaLcDXBJBmBNjzdDCh9jx7C2MKzZ9+jXO70Ql/Bgfmzlw9ffbngWb2Ti8EEgF403omMebVhXX5ZnR+eecAV5nVr2rMFWA455RY08dN1sivUcv/vZvt1voCETSW2z/x81y1TRLedOlNKdGOa7NU/EsXJISBaUfUblrEulO+4hnbFs2/KWtUrRtHzcPDEOhYfONCrNqQa/4p15PHCVKUZVP9Gb/6cIlgT0SjtIb1u8V9/5Agzd7/UPB0VYY+xmwjad8dYVx5ZQWTyRuHMj71YF6N+gzue+n3hJ8tVnWuw1/cx1o7uDfEqhmxuv6BtBl078q9DHPm3JI8rGchxkWRzuhCFutoie2Oy9aK0WNBjhorCvFDsEKWSPAUZ1OqYrLVhZUyQ34Q8IZJNBFa2WEcc9XYGERAdMn5Bs58noGzxXV3sNRpiQ6f+3fCNEUIRPlYhg2+eI++vUyV7rEuOEAktJKzdshsmk9p0PERmiU4mAEvAO+uCJFXrh/yj6LZ+PloKU/c8vzL5ixNcaFW8k4TZuCm5JoljEH0/lF2SChgv7VAmYYqNPSzNFkgTr1pNqSBzyVEqL29eTClVK0vkE9L4XwbeLahFpkeU=
  file: build/outputs/apk/release/a11y-ally-release.apk
  skip_cleanup: true
  on:
    branch: master
