env:
  global:
    secure: ApwvULTvJ7Nj72bfVThK7poU/WEybEaJNW8AsoriI7fpdz+ZFO4fgGAIfs0gAFdYIntohYKPymueuMoOXPX0CeqHl4YnZ6/ojPl/Go2+gIOk4QZdbhuMyPKyp+gMKWqaG3/kjNBkzpxWIHPwZlP/Q86y3jSW4Fy+jVsJs37o2KspLXne30mw4OId2xJIpHTfKL0XR3HP9xg9O7DMCGcXiPhfSVOKErx/zsZplZq2g7/p2j2qU4jlmuSIzCl43RHtmeajoN5mmmukk5DFVZ2tlwDCthwRsDxTIInyfKG1Dop/68l3GBgBFPzs6vy1E1tMxLiWAbNcUJ43d2yGKBYhQgE81Dackh4gy5mefTVZkKUfS2Ad5EiXmaapxsP5LP1KBG1CDlWSudFHmWBxqhiAEeq/Oh2ZS86ns6UkhEIW1o4/n5Cha4uOV4kAroJcPRausqCvyyEKOd+undQVB8393Qpyu/7s+Sg0BOkXLaCmwFA1ZhTaNJOPFNl3/IJs6mUb6sxhvGsqmBBubVoLsh+C2n97n70H8nYeXld4mTvvmNdrlxiaHANWYMrmyLsrIDGx+nSGpNLufQZiKtn9lY+5YmgJjyRjImSEA7S7cV5EVo27QYj15BbUpyq++07lgZvI5n3jTUArrJtbs8mQeK87dRXI99cr9UGRFfXbdEDKAEg=

language: java

before_install:
- openssl aes-256-cbc -K $encrypted_e375928ce4bc_key -iv $encrypted_e375928ce4bc_iv
  -in config/a11y-ally-release.jks.enc -out config/a11y-ally-release.jks
  -d

script:
- ./gradlew

deploy:
  provider: releases
  api_key:
    secure: aWc/75tkbiVuve/Tbg9U4wB/Mm4id8IXcgVm4YsQZxHKxouaOo44gCksjINdJP99WOcG8Oq/slKykaLcDXBJBmBNjzdDCh9jx7C2MKzZ9+jXO70Ql/Bgfmzlw9ffbngWb2Ti8EEgF403omMebVhXX5ZnR+eecAV5nVr2rMFWA455RY08dN1sivUcv/vZvt1voCETSW2z/x81y1TRLedOlNKdGOa7NU/EsXJISBaUfUblrEulO+4hnbFs2/KWtUrRtHzcPDEOhYfONCrNqQa/4p15PHCVKUZVP9Gb/6cIlgT0SjtIb1u8V9/5Agzd7/UPB0VYY+xmwjad8dYVx5ZQWTyRuHMj71YF6N+gzue+n3hJ8tVnWuw1/cx1o7uDfEqhmxuv6BtBl078q9DHPm3JI8rGchxkWRzuhCFutoie2Oy9aK0WNBjhorCvFDsEKWSPAUZ1OqYrLVhZUyQ34Q8IZJNBFa2WEcc9XYGERAdMn5Bs58noGzxXV3sNRpiQ6f+3fCNEUIRPlYhg2+eI++vUyV7rEuOEAktJKzdshsmk9p0PERmiU4mAEvAO+uCJFXrh/yj6LZ+PloKU/c8vzL5ixNcaFW8k4TZuCm5JoljEH0/lF2SChgv7VAmYYqNPSzNFkgTr1pNqSBzyVEqL29eTClVK0vkE9L4XwbeLahFpkeU=
  file: build/outputs/apk/release/a11y-ally-release.apk
  skip_cleanup: true
  on:
    branch: master
