env:
  global:
  # ANDROID_SIGNING_PASSWORD
  - secure: KmZ88eIr9tDOGXqY1LXzAkjonEm2PxzV2X7lhsBDo7x1AjdEumN8Q6Ekp9AxJ2iNhdDlEgmv/4FVzm9pq1Jd6FcQvzqtNTcyDtIOiIECSb6CKmKjAo/u6rQk7AoIQ98AjVxV5Ksr9Xal8DRphEHghc9KPx1tmuqS1N4tEgd5YiKm/1A8kHH+ZypBk5hoxjF1GIg1d/TLxVQnhNgJDlZSwLVPNK9+ZSpT+7A79YlzZMAqPyrChHJOd/JYr+fbP/C57iel3C13VbeBWwK7YB6HbQrIEAp68sr8s68mOeg47Y4SWqRF7mP2JGzb8hiD+f7H6EkWE7zKn6GMNuQRWE3olcAcigUkPaFu1aFeuN/KCsDYjLddl/v8buMZS30XEJPi7+XtTXDgQflKcbl5tkiLQd8S6GRupcwVatv8K/cQMFVhfHdXk45ZYSfkngI6+WYxBMgBPEeXwWopUkD+fmuCjhPmoUHbLU5JDaAotHs7wLqCYCI+JC7bQ34AevFifC+If3uU6o2sX6VIM27Jls/56tFfC0jU2Ld9qvvvVLx+lMckefFUpZ2Mn26pnWtN8j/RAacMPLNYn3FQ4gL5j2AbfcQByrjZX9yDvNzcTrCTuWhY9T4Hf9Jv7VeTiZ6ADrwkOxUSafA4237v2YoIqq7hpt7WLwlvNlIFTfmMTd8DGKg=

language: android

jdk:
  - openjdk10

before_install:
- openssl aes-256-cbc -K $encrypted_e375928ce4bc_key -iv $encrypted_e375928ce4bc_iv
  -in config/a11y-ally-secrets.zip.enc -out config/a11y-ally-secrets.zip
  -d
- unzip config/a11y-ally-secrets.zip -d config

# Disable default install task
install: true

script:
- ./gradlew

before_deploy:
- git config --local user.name "Dustin Toff"
- git config --local user.email "me@dustintoff.com"
- apkanalyzer=./build/android-sdk-root/cmdline-tools/latest/bin/apkanalyzer
- chmod +x $apkanalyzer
- version_code="$($apkanalyzer manifest version-code build/outputs/apk/release/a11y-ally-release.apk)"
- git tag "version-code-${version_code}" || echo "Release already tagged"

deploy:
- provider: releases
  api_key:
    secure: aWc/75tkbiVuve/Tbg9U4wB/Mm4id8IXcgVm4YsQZxHKxouaOo44gCksjINdJP99WOcG8Oq/slKykaLcDXBJBmBNjzdDCh9jx7C2MKzZ9+jXO70Ql/Bgfmzlw9ffbngWb2Ti8EEgF403omMebVhXX5ZnR+eecAV5nVr2rMFWA455RY08dN1sivUcv/vZvt1voCETSW2z/x81y1TRLedOlNKdGOa7NU/EsXJISBaUfUblrEulO+4hnbFs2/KWtUrRtHzcPDEOhYfONCrNqQa/4p15PHCVKUZVP9Gb/6cIlgT0SjtIb1u8V9/5Agzd7/UPB0VYY+xmwjad8dYVx5ZQWTyRuHMj71YF6N+gzue+n3hJ8tVnWuw1/cx1o7uDfEqhmxuv6BtBl078q9DHPm3JI8rGchxkWRzuhCFutoie2Oy9aK0WNBjhorCvFDsEKWSPAUZ1OqYrLVhZUyQ34Q8IZJNBFa2WEcc9XYGERAdMn5Bs58noGzxXV3sNRpiQ6f+3fCNEUIRPlYhg2+eI++vUyV7rEuOEAktJKzdshsmk9p0PERmiU4mAEvAO+uCJFXrh/yj6LZ+PloKU/c8vzL5ixNcaFW8k4TZuCm5JoljEH0/lF2SChgv7VAmYYqNPSzNFkgTr1pNqSBzyVEqL29eTClVK0vkE9L4XwbeLahFpkeU=
  file:
  - build/outputs/apk/release/a11y-ally-release.apk
  - build/outputs/bundle/release/a11y-ally.aab
  - build/outputs/mapping/release/*
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    tags: false
- provider: script
  script: ./gradlew publish
  skip_cleanup: true
  on:
    branch: master
    tags: false
